# Goonstation Documentation Publisher

name: Code Documentation

on:
  push:
    branches: [master]

jobs:
  documentation:
    name: Code Documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Install Dependencies
        run: |
          goonstation/tools/ci/install_spaceman_dmm.sh dmdoc
          touch goonstation/+secret/__secret.dme

      - name: Run dmdoc
        run: |
          cd goonstation
          ~/dmdoc

      - name: Deploy Documentation
        uses: JamesIves/github-pages-deploy-action@3.5.9
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: dmdoc
          SINGLE_COMMIT: true
