# Updates the Goonstation submodule

name: "Update Submodule"

on:
  schedule:
  - cron: "*/20 * * * *"
  workflow_dispatch:

jobs:
    update:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4

        - run: |
            git submodule update --init
            git config --local user.name robuddybot
            git config --local user.email 65057909+robuddybot@users.noreply.github.com
            git submodule update --remote --merge
            commit_msg=$(git commit -m "Updated Submodule" -a)
            ./test_nothing.sh "$commit_msg"

        - uses: ad-m/github-push-action@master
          with:
            github_token: ${{ secrets.ROBUDDYBOT_PAT }}

        - name: Repository Dispatch
          uses: peter-evans/repository-dispatch@v3
          with:
            token: ${{ secrets.ROBUDDYBOT_PAT_FULL }}
            event-type: update-documentation
