# Updates the Goonstation submodule

name: "Update Submodule"

on:
  schedule:
  - cron: "*/5 * * * *"

jobs:
    update:
      runs-on: ubuntu-latest
      steps:

        - uses: actions/checkout@v2
          with:
            submodules: true

        - run: |
            git config user.name robuddybot
            git config user.email 65057909+robuddybot@users.noreply.github.com
            git submodule update --remote --merge
            git commit -m "Updated Submodule"
            git push -f
